name: imagery_accessor
channels:
- conda-forge
- default
dependencies:
- python>=3.7
- earthpy
- geopandas
- matplotlib
- numpy
- pandas
- rasterio
- rioxarray
- shapely
- xarray
# Testing packages
- coverage
- pytest
- pytest-mock
